/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

// Tree class 
public class BinaryTree {
    private Node root;

    public BinaryTree(Squirrel rootData) {
        this.root = new Node(rootData);
    }

    public Node getRoot() {
        return root;
    }

     public void attachLeft(Node parent, Squirrel data) {
        Node newNode = new Node(data);
        parent.setLeft(newNode);
    }

     public void attachRight(Node parent, Squirrel data) {
        Node newNode = new Node(data);
        parent.setRight(newNode);
    }

    // List Tree Level by level left to right
    public void traversePreOrder(Node node) {
         if (node == null) return;

        System.out.println(node.getData().getName());
        traversePreOrder(node.getLeft());
        traversePreOrder(node.getRight());
    }
}
