/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Node {
    private Squirrel data;
    private Node left;
    private Node right;

     public Node(Squirrel data) {
         this.data = data;
    }
//display
     public Squirrel getData() {
         return data;
    }
//getters
    public Node getLeft() {
        return left;
    }

    public Node getRight() {
        return right;
    }
// setters
    public  void setLeft(Node left) {
        this.left = left;
    }

    public  void setRight(Node right)  {
        this.right = right;
    }
}
