/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

public class Squirrel {
  private final String name;
 //Had to add public to this since it kept throwing errors
  public Squirrel(String name) {
    this.name = name;
  }
 
  public String getName() {
    return this.name;
  }
}