/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import org.junit.jupiter.api.Test;

public class AppTest {

    @Test
    public void testMainRuns() {
        assertDoesNotThrow(() -> App.main(new String[]{}));
    }
}
