/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

public class BinaryTreeTest {

    @Test
    public void testRootCreation() {
        BinaryTree tree = new BinaryTree(new Squirrel("Rooty"));
        assertEquals("Rooty", tree.getRoot().getData().getName());
    }

    @Test
    public void testAttachLeft() {
         BinaryTree tree = new BinaryTree(new Squirrel("Root"));
         Node root = tree.getRoot();

        tree.attachLeft(root, new Squirrel("Lefty"));
        assertEquals("Lefty", root.getLeft().getData().getName());
    }

    @Test
    public void testAttachRight() {
        BinaryTree tree = new BinaryTree(new Squirrel("Root"));
        Node root = tree.getRoot();

        tree.attachRight(root, new Squirrel("Righty"));
        assertEquals("Righty", root.getRight().getData().getName());
    }

    @Test
    public void testPreOrderTraversalOutput() {
        BinaryTree tree = new BinaryTree(new Squirrel("Root"));
        tree.attachLeft(tree.getRoot(), new Squirrel("L"));
        tree.attachRight(tree.getRoot(), new Squirrel("R"));

        // Capture console output
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));

        tree.traversePreOrder(tree.getRoot());

        String output = out.toString().trim().replace("\r", "");
        assertEquals("Root\nL\nR", output);
    }
}
