/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

public class NodeTest {

    @Test
    public void testNodeStoresData() {
        Squirrel s = new Squirrel("Rocky");
        Node node = new Node(s);

         assertEquals("Rocky", node.getData().getName());
    }

    @Test
    public void testSetLeftChild() {
        Node parent = new Node(new Squirrel("Parent"));
        Node child = new Node(new Squirrel("ChildLeft"));

        parent.setLeft(child);

        assertEquals("ChildLeft", parent.getLeft().getData().getName());
    }

    @Test
    public void  testSetRightChild() {
        Node parent = new Node(new Squirrel("Parent"));
        Node child = new Node(new Squirrel("ChildRight"));

        parent.setRight(child);

         assertEquals("ChildRight", parent.getRight().getData().getName());
    }
}
