/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

public class SquirrelTest {

    @Test
    public void testGetName() {
        Squirrel s = new Squirrel("Benny");
         assertEquals("Benny", s.getName());
    }
}
